Repository coala/devops, pull requests merged in 2018-05, with the labels that each got.

#101 planet.ini: Add Kriti Rohilla's blog
  venus/planet/planet.ini
Labels: process/pending review

#102 planet.ini: Add Vamshi99's blog
  venus/planet/planet.ini
Labels: process/pending review

#103 planet.ini: Add sangamcse's blog
  venus/planet/planet.ini
Labels: process/pending review

#110 planet.ini: Add yzgyyang's blog
  venus/planet/planet.ini
Labels: process/pending_review

#109 planet.ini: Add sks444's gsoc feed
  venus/planet/planet.ini
Labels: process/pending_review, process/wip

#115 planet.ini: Update blog feed for RJ722
  venus/planet/planet.ini
Labels: process/pending_review

#113 planet.ini: Add RaiVaibhav's blog
  venus/planet/planet.ini
Labels: process/pending_review

#114 planet.ini: Add nitanshu's blog
  venus/planet/planet.ini
Labels: process/pending_review

#111 Add nemaniarjun's blog
  venus/planet/planet.ini
Labels: process/pending_review

#112 Adds palash25 gsoc feed
  venus/planet/planet.ini
Labels: process/pending_review, process/wip
